language: python
python:
    - 2.7
    - 3.4
install:
    - pip install .
    - pip install zope.testrunner zope.testing zope.i18n zope.tal zope.component zope.security
script:
    - zope-testrunner --test-path src
notifications:
    email: false
sudo: false
